name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        submodules: recursive

    - name: Run build
      run: echo "Hello, world! This is where you can add build commands."
